spring:
  application:
    name: crudDemo
  datasource:
    url: jdbc:postgresql://localhost:5432/student_tracker
    username: postgres1
    password: postgres1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update